//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bkg_selection_H
#define METASPRITE_bkg_selection_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bkg_selection_TILE_ORIGIN 0
#define bkg_selection_TILE_W 8
#define bkg_selection_TILE_H 8
#define bkg_selection_WIDTH 256
#define bkg_selection_HEIGHT 256
#define bkg_selection_TILE_COUNT 80
#define bkg_selection_PALETTE_COUNT 1
#define bkg_selection_COLORS_PER_PALETTE 4
#define bkg_selection_TOTAL_COLORS 4
#define bkg_selection_MAP_ATTRIBUTES 0
extern const unsigned char bkg_selection_map[1024];
#define bkg_selection_map_attributes bkg_selection_map

BANKREF_EXTERN(bkg_selection)

extern const uint8_t bkg_selection_tiles[1280];

#endif
