//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bkg_md_std_H
#define METASPRITE_bkg_md_std_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bkg_md_std_TILE_ORIGIN 0
#define bkg_md_std_TILE_W 8
#define bkg_md_std_TILE_H 8
#define bkg_md_std_WIDTH 160
#define bkg_md_std_HEIGHT 144
#define bkg_md_std_TILE_COUNT 0
#define bkg_md_std_PALETTE_COUNT 1
#define bkg_md_std_COLORS_PER_PALETTE 4
#define bkg_md_std_TOTAL_COLORS 4
#define bkg_md_std_MAP_ATTRIBUTES 0
extern const unsigned char bkg_md_std_map[360];
#define bkg_md_std_map_attributes bkg_md_std_map

BANKREF_EXTERN(bkg_md_std)


#endif
