//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_border_default_H
#define METASPRITE_border_default_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define border_default_TILE_ORIGIN 0
#define border_default_TILE_W 8
#define border_default_TILE_H 8
#define border_default_WIDTH 256
#define border_default_HEIGHT 224
#define border_default_TILE_COUNT 44
#define border_default_PALETTE_COUNT 1
#define border_default_COLORS_PER_PALETTE 16
#define border_default_TOTAL_COLORS 16
#define border_default_MAP_ATTRIBUTES 0
#define border_default_MAP_ATTRIBUTES_WIDTH 32
#define border_default_MAP_ATTRIBUTES_HEIGHT 28
#define border_default_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define border_default_MAP_ATTRIBUTES_PACKED_HEIGHT 28

BANKREF_EXTERN(border_default)

extern const palette_color_t border_default_palettes[16];
extern const uint8_t border_default_tiles[1408];

extern const unsigned char border_default_map[1792];
#define border_default_map_attributes border_default_map

#endif
