//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(spr_star)

const palette_color_t spr_star_palettes[4] = {
	RGB8(255,255,255), RGB8(176,176,176), RGB8( 99, 99, 99), RGB8(  0,  0,  0)
	
};

const uint8_t spr_star_tiles[16] = {
	0x08,0x08,0x14,0x1c,
	0x6b,0x77,0x5d,0x63,
	0x3e,0x22,0x36,0x2a,
	0x2a,0x3e,0x36,0x36
	
};

const metasprite_t spr_star_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const spr_star_metasprites[1] = {
	spr_star_metasprite0
};
