//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_spr_star_H
#define METASPRITE_spr_star_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spr_star_TILE_ORIGIN 0
#define spr_star_TILE_W 8
#define spr_star_TILE_H 8
#define spr_star_WIDTH 8
#define spr_star_HEIGHT 8
#define spr_star_TILE_COUNT 1
#define spr_star_PALETTE_COUNT 1
#define spr_star_COLORS_PER_PALETTE 4
#define spr_star_TOTAL_COLORS 4
#define spr_star_PIVOT_X 4
#define spr_star_PIVOT_Y 4
#define spr_star_PIVOT_W 8
#define spr_star_PIVOT_H 8
extern const metasprite_t* const spr_star_metasprites[1];

BANKREF_EXTERN(spr_star)

extern const palette_color_t spr_star_palettes[4];
extern const uint8_t spr_star_tiles[16];

#endif
