//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tiles_gonefishing_H
#define METASPRITE_tiles_gonefishing_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_gonefishing_TILE_ORIGIN 96
#define tiles_gonefishing_TILE_W 8
#define tiles_gonefishing_TILE_H 8
#define tiles_gonefishing_WIDTH 96
#define tiles_gonefishing_HEIGHT 96
#define tiles_gonefishing_TILE_COUNT 111
#define tiles_gonefishing_PALETTE_COUNT 1
#define tiles_gonefishing_COLORS_PER_PALETTE 4
#define tiles_gonefishing_TOTAL_COLORS 4
#define tiles_gonefishing_MAP_ATTRIBUTES 0

BANKREF_EXTERN(tiles_gonefishing)

extern const uint8_t tiles_gonefishing_tiles[1776];

extern const unsigned char tiles_gonefishing_map[144];
#define tiles_gonefishing_map_attributes tiles_gonefishing_map

#endif
