//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tiles_general_H
#define METASPRITE_tiles_general_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_general_TILE_ORIGIN 0
#define tiles_general_TILE_W 8
#define tiles_general_TILE_H 8
#define tiles_general_WIDTH 128
#define tiles_general_HEIGHT 48
#define tiles_general_TILE_COUNT 96
#define tiles_general_PALETTE_COUNT 1
#define tiles_general_COLORS_PER_PALETTE 4
#define tiles_general_TOTAL_COLORS 4

BANKREF_EXTERN(tiles_general)

extern const palette_color_t tiles_general_palettes[4];
extern const uint8_t tiles_general_tiles[1536];


#endif
