//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tiles_sgb_gonefishing_H
#define METASPRITE_tiles_sgb_gonefishing_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_sgb_gonefishing_TILE_ORIGIN 0
#define tiles_sgb_gonefishing_TILE_W 8
#define tiles_sgb_gonefishing_TILE_H 8
#define tiles_sgb_gonefishing_WIDTH 96
#define tiles_sgb_gonefishing_HEIGHT 96
#define tiles_sgb_gonefishing_TILE_COUNT 114
#define tiles_sgb_gonefishing_PALETTE_COUNT 8
#define tiles_sgb_gonefishing_COLORS_PER_PALETTE 4
#define tiles_sgb_gonefishing_TOTAL_COLORS 32

BANKREF_EXTERN(tiles_sgb_gonefishing)

extern const palette_color_t tiles_sgb_gonefishing_palettes[32];
extern const uint8_t tiles_sgb_gonefishing_tiles[1824];


#endif
