//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_uimap_select_curtain_H
#define METASPRITE_uimap_select_curtain_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define uimap_select_curtain_TILE_ORIGIN 0
#define uimap_select_curtain_TILE_W 8
#define uimap_select_curtain_TILE_H 8
#define uimap_select_curtain_WIDTH 160
#define uimap_select_curtain_HEIGHT 32
#define uimap_select_curtain_TILE_COUNT 0
#define uimap_select_curtain_PALETTE_COUNT 1
#define uimap_select_curtain_COLORS_PER_PALETTE 4
#define uimap_select_curtain_TOTAL_COLORS 4
#define uimap_select_curtain_MAP_ATTRIBUTES 0
extern const unsigned char uimap_select_curtain_map[80];
#define uimap_select_curtain_map_attributes uimap_select_curtain_map

BANKREF_EXTERN(uimap_select_curtain)


#endif
