//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_uimap_dialogbox_H
#define METASPRITE_uimap_dialogbox_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define uimap_dialogbox_TILE_ORIGIN 0
#define uimap_dialogbox_TILE_W 8
#define uimap_dialogbox_TILE_H 8
#define uimap_dialogbox_WIDTH 160
#define uimap_dialogbox_HEIGHT 40
#define uimap_dialogbox_TILE_COUNT 0
#define uimap_dialogbox_PALETTE_COUNT 1
#define uimap_dialogbox_COLORS_PER_PALETTE 4
#define uimap_dialogbox_TOTAL_COLORS 4
#define uimap_dialogbox_MAP_ATTRIBUTES 0

BANKREF_EXTERN(uimap_dialogbox)


extern const unsigned char uimap_dialogbox_map[100];
#define uimap_dialogbox_map_attributes uimap_dialogbox_map

#endif
